# Generated by Django 4.2.7 on 2023-12-05 18:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("update_at", models.DateField(auto_created=True)),
                ("created_at", models.DateField(auto_created=True)),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("product_slug", models.SlugField(unique=True)),
                ("product_description", models.TextField()),
                ("product_price", models.IntegerField(default=0)),
                ("product_demo_price", models.IntegerField(default=0)),
                ("quantity", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductMetaInformation",
            fields=[
                ("update_at", models.DateField(auto_created=True)),
                ("created_at", models.DateField(auto_created=True)),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "product_measuring_unit",
                    models.CharField(
                        blank=True,
                        choices=[("KG", "KG"), ("ML", "ML"), ("L", "L"), (None, None)],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "product_quantity",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("is_restrict", models.BooleanField(default=False)),
                ("restrict_quantity", models.IntegerField()),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta_info",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductImages",
            fields=[
                ("update_at", models.DateField(auto_created=True)),
                ("created_at", models.DateField(auto_created=True)),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_images", models.ImageField(upload_to="products")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
